### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by heeyeon-developer** [sundayTen/pokr-server#22]
- [x] ERD 툴 선정
- [x] ERD 작성
- [ ] ERD 후기 작성

**Comment by tagrn** [comment]
1차 ERD 작성 완료. ERD 후기는 작성하지 않아도 될 듯하다. 왜냐하면 테이블 개수가 10개가 넘지 않기 때문.

10개가 넘는다면 후기 작성 후, 무료 플랜을 얻도록 한다.
